general {
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = $HOME/Pictures/Wallpapers/default.png
    brightness = 0.55
}

label {
    monitor =

    text = $TIME

    color = rgba(217, 224, 238, 1.0)

    font_size = 88
    font_family = JetBrainsMono Nerd Font Bold

    position = 0, 155

    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:60000] date +"%A, %d %B"

    color = rgba(122, 162, 247, 1.0)

    font_size = 18
    font_family = JetBrainsMono Nerd Font Bold

    position = 0, 78

    halign = center
    valign = center
}

input-field {
    monitor =

    size = 340, 54

    outline_thickness = 2

    dots_size = 0.22
    dots_spacing = 0.28
    dots_center = true

    outer_color = rgba(122, 162, 247, 1.0)
    inner_color = rgba(30, 29, 47, 0.92)

    font_color = rgba(217, 224, 238, 1.0)
    font_family = JetBrainsMono Nerd Font

    check_color = rgba(166, 227, 161, 1.0)
    fail_color = rgba(242, 143, 173, 1.0)

    fade_on_empty = false

    placeholder_text = <span foreground="##D9E0EE">Password</span>
    fail_text = Wrong password

    rounding = 8

    position = 0, -25

    halign = center
    valign = center
}
